name = "redirect"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]
workers_dev = true

routes = [
  
  { pattern = "api24-normal.tiktokv.com.redirect.benxx.workers.dev", custom_domain = true },  

  ]

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
